#!/usr/bin/env python3

import dataset
from itertools import groupby

db_path = os.path.expanduser('~/soups.sqlite')
db = dataset.connect('sqlite:///{}'.format(db_path))

soups_table = db['soups']

# unique by day and location
key = lambda r: (r['location_name'], r['timestamp'])

for grp, items in groupby(sorted(soups_table, key=key), key=key):
    items = list(items)
    print('{} {}'.format(len(items), items[0]))
